import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#eef4ff' },
  container: { flex: 1, backgroundColor: '#eef4ff', paddingTop: 0 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, marginTop: 12, marginBottom: 12 },
  appTitle: { fontSize: 26, fontWeight: '800', color: '#111827' },
  pageSubtitle: { fontSize: 15, color: '#6b7280', marginTop: 6 },
  settingsButton: { width: 44, height: 44, borderRadius: 16, backgroundColor: '#ffffff', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  pointsCard: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 20, padding: 16, borderRadius: 20, backgroundColor: '#ffffff', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6, marginBottom: 20 },
  pointsTextGroup: { marginLeft: 12 },
  pointsLabel: { fontSize: 12, color: '#6b7280' },
  pointsValue: { fontSize: 20, fontWeight: '800', color: '#111827', marginTop: 2 },
  scroll: { paddingHorizontal: 16, paddingBottom: 80 },
  topicCard: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 20, marginBottom: 12, minHeight: 80, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  cardIconWrapper: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)' },
  cardTextGroup: { marginLeft: 16, flex: 1 },
  cardTitle: { color: '#ffffff', fontSize: 17, fontWeight: '700', marginBottom: 6 },
  cardSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: 13, lineHeight: 18 },
  title: { fontSize: 22, fontWeight: '800', color: '#111827', marginHorizontal: 16, marginBottom: 8 },
  description: { fontSize: 15, color: '#6b7280', marginHorizontal: 16 },
  starInfo: { fontSize: 15, color: '#6b7280', marginHorizontal: 16, marginBottom: 16 },
  levelGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', paddingHorizontal: 16 },
  levelButton: { backgroundColor: '#10b981', margin: 4, padding: 12, borderRadius: 10, alignItems: 'center', width: 60 },
  levelText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  starRow: { flexDirection: 'row', marginTop: 6 },
  introHeader: { position: 'relative', borderRadius: 24, marginHorizontal: 16, padding: 10, paddingBottom: 12, marginBottom: 6, minHeight: 48, justifyContent: 'center', marginTop: 12 },
  headerBack: { position: 'absolute', left: 16, top: 18, width: 36, height: 36, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  headerBackInline: { width: 36, height: 36, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  introTitle: { color: '#ffffff', fontSize: 20, fontWeight: '800', marginBottom: 0, flexShrink: 1 },
  introSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: 14, lineHeight: 20, marginTop: 6, flexShrink: 1 },
  headerExamplesRow: { flexDirection: 'row', flexWrap: 'wrap' },
  headerExampleChip: { backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 12, paddingVertical: 6, paddingHorizontal: 10, marginBottom: 6, marginRight: 6 },
  headerExampleText: { color: '#ffffff', fontSize: 12, lineHeight: 16 },
  introScroll: { paddingHorizontal: 16, paddingBottom: 80 },
  sectionTitle: { fontSize: 17, fontWeight: '800', color: '#111827', marginBottom: 10, marginTop: 8 },
  examplesRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  exampleCard: { backgroundColor: '#ffffff', borderRadius: 16, padding: 12, marginBottom: 10, width: '48%', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  exampleText: { fontSize: 14, color: '#111827', lineHeight: 20 },
  introText: { fontSize: 15, color: '#4b5563', lineHeight: 24, marginTop: 8 },
  descriptionCard: { backgroundColor: '#ffffff', borderRadius: 20, marginHorizontal: 16, padding: 16, marginBottom: 16, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroCard: { backgroundColor: '#ffffff', borderRadius: 20, marginHorizontal: 16, padding: 18, marginBottom: 16, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroEquation: { fontSize: 26, fontWeight: '800', textAlign: 'center', marginBottom: 12 },
  heroEquationText: { fontSize: 26, fontWeight: '800' },
  heroDivider: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 8 },
  heroDescription: { fontSize: 14, color: '#6b7280', lineHeight: 20, textAlign: 'center' },
  primaryButton: { marginTop: 20, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 14, borderRadius: 18, paddingHorizontal: 24, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  buttonIcon: { marginRight: 10 },
  primaryButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  
  // Addition Intro
  equationBoxRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 12, gap: 6, flexWrap: 'wrap' },
  numberBox: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, minWidth: 45, alignItems: 'center' },
  numberBoxText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  operatorText: { fontSize: 18, fontWeight: '700', color: '#111827', marginHorizontal: 3 },
  
  // Ordering Intro
  orderingSequence: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 10, gap: 3 },
  orderingNumber: { fontSize: 24, fontWeight: '700' },
  orderingComma: { fontSize: 18, color: '#111827', marginHorizontal: 2 },
  orderingArrow: { alignItems: 'center', marginVertical: 6 },
  
  // Sudoku Intro
  sudokuContainer: { alignItems: 'center', marginVertical: 10 },
  sudokuRow: { flexDirection: 'row' },
  sudokuCell: { width: 50, height: 50, justifyContent: 'center', alignItems: 'center', borderColor: '#d1d5db', borderWidth: 1 },
  sudokuText: { fontSize: 16, fontWeight: '700', color: '#111827' },
  
  // Counting Intro
  countingHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  countingBadge: { backgroundColor: '#ffffff', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 12, marginBottom: 6 },
  countingBadgeText: { color: '#0ea5e9', fontSize: 16, fontWeight: '800' },
  countingHeaderTitles: { flex: 1 },
  countingNumbersRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, marginBottom: 14 },
  countingNumber: { fontSize: 30, fontWeight: '700' },
  applesRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, marginBottom: 20 },
  appleBubble: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#fef2f2', justifyContent: 'center', alignItems: 'center' },
  appleEmoji: { fontSize: 24 },
  exampleCardLarge: { width: '48%', minHeight: 110 },
  exampleCardLabel: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 6 },
  exampleCardText: { fontSize: 13, color: '#4b5563', lineHeight: 20 },
  exampleAppleRow: { flexDirection: 'row', marginTop: 12, gap: 8 },
  appleEmojiSmall: { fontSize: 18 },
  
  // Geometry Intro
  shapesRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', marginVertical: 20 },
  shapeItem: { alignItems: 'center', gap: 8 },
  shapeLabel: { fontSize: 12, color: '#6b7280', fontWeight: '600' },
  triangle: { width: 0, height: 0, backgroundColor: 'transparent', borderLeftWidth: 30, borderRightWidth: 30, borderBottomWidth: 52, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#f97316' },
  square: { width: 60, height: 60, borderRadius: 8 },
  circle: { width: 60, height: 60, borderRadius: 30 },
  
  // Word Problems Intro
  wordProblemScene: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginVertical: 16, flexWrap: 'wrap' },
  cartContainer: { justifyContent: 'center', alignItems: 'center' },
  priceTagsRow: { flexDirection: 'row', gap: 12 },
  priceTag: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12, position: 'relative' },
  priceText: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  questionMark: { fontSize: 40, fontWeight: '700', color: '#6b7280' },
  
  // Video Lessons Intro
  videoPlayerContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 20, marginVertical: 12 },
  videoPlaceholder: { width: 120, height: 80, backgroundColor: '#e5e7eb', borderRadius: 12, justifyContent: 'center', alignItems: 'center', position: 'relative' },
  playButtonOverlay: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#3b82f6', justifyContent: 'center', alignItems: 'center' },
  bookStack: { width: 80, height: 100, position: 'relative' },
  book: { position: 'absolute', width: 70, height: 80, borderRadius: 4 },
  
  // Level Selector
  levelHeader: { borderRadius: 28, marginHorizontal: 20, padding: 16, paddingBottom: 18, marginBottom: 12, flexDirection: 'row', alignItems: 'flex-start', marginTop: 12 },
  headerTitleGroup: { flex: 1, marginLeft: 16 },
  levelSelectorTitle: { color: '#ffffff', fontSize: 24, fontWeight: '800', marginBottom: 4 },
  levelSelectorSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 14, lineHeight: 20 },
  levelScroll: { paddingHorizontal: 20, paddingBottom: 30 },
  selectLevelTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 16, marginTop: 8 },
  
  // Level Button
  levelButtonContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, paddingRight: 12 },
  levelCircle: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  levelNumber: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  starsContainer: { flexDirection: 'row', gap: 4 },
  
  // Difficulty Indicator
  difficultyIndicator: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 24, paddingHorizontal: 12 },
  easiestSelectorLabel: { fontSize: 12, color: '#10b981', fontWeight: '600' },
  hardestSelectorLabel: { fontSize: 12, color: '#ef4444', fontWeight: '600' },
  
  // Level Detail Screen
  levelDetailCard: { backgroundColor: '#ffffff', borderRadius: 28, width: '100%', marginBottom: 0, overflow: 'visible', alignSelf: 'stretch', marginHorizontal: 20 },
  levelDetailHeader: { position: 'relative', borderRadius: 28, marginHorizontal: 20, paddingTop: 32, padding: 18, paddingBottom: 20, marginBottom: 12, minHeight: 64, marginTop: 12 },
  levelDetailHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  levelDetailHeaderBack: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 12, marginRight: 12 },
  headerContentGroup: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 60 },
  categoryIcon: { width: 76, height: 76, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  screenHeaderIcon: { width: 48, height: 48, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginRight: 12, backgroundColor: 'rgba(255,255,255,0.18)' },
  levelDetailHeaderTitleGroup: { flex: 1, justifyContent: 'center' },
  introHeaderContent: { marginTop: 8, flexDirection: 'row', alignItems: 'center' },
  introHeaderTitleGroup: { flex: 1, marginLeft: 12, justifyContent: 'center', minHeight: 42 },
  practiceHeaderContent: { marginTop: 16, flexDirection: 'row', alignItems: 'center' },
  practiceHeaderTextGroup: { flex: 1 },
  levelTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginBottom: 4 },
  levelSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 13, lineHeight: 18 },
  levelDetailScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 12 },
  fullScreenScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 20 },
  levelBody: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 24 },
  levelBodyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  easiestBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelDetailButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f8fafc', borderRadius: 20, paddingVertical: 16, paddingHorizontal: 12, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  levelDetailCircle: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  levelDetailNumber: { color: '#ffffff', fontSize: 20, fontWeight: '800' },
  levelDetailInfo: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  levelDetailLabel: { fontSize: 16, fontWeight: '700', color: '#111827' },
  levelDetailStars: { flexDirection: 'row', alignItems: 'center' },
  starSpacing: { marginLeft: 6 },
  levelBodyFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingHorizontal: 20 },
  hardestBadge: { backgroundColor: '#fee2e2', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  easiestLabel: { fontSize: 12, color: '#16a34a', fontWeight: '700' },
  hardestLabel: { fontSize: 12, color: '#dc2626', fontWeight: '700' },

  // Level Grid Screen (New Layout)
  levelGridHeader: { position: 'relative', borderRadius: 28, marginHorizontal: 20, paddingTop: 32, padding: 10, paddingBottom: 12, marginBottom: 6, minHeight: 48, marginTop: 12 },
  levelGridHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  levelGridHeaderBack: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 12, marginRight: 12 },
  levelGridHeaderContent: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  levelGridHeaderIcon: { width: 48, height: 48, borderRadius: 16, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)', marginRight: 12 },
  levelGridHeaderText: { flex: 1 },
  levelGridTitle: { color: '#ffffff', fontSize: 20, fontWeight: '800', marginBottom: 3 },
  levelGridDescription: { color: 'rgba(255,255,255,0.9)', fontSize: 13, lineHeight: 18 },
  levelGridScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 12 },
  levelGridCard: { backgroundColor: '#ffffff', borderRadius: 28, marginHorizontal: 20, padding: 20, marginBottom: 16, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  levelGridSelectTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 20 },
  levelGridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 0 },
  levelGridItem: { width: '48%', backgroundColor: '#f8fafc', borderRadius: 16, padding: 16, alignItems: 'center', marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  levelGridCircle: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  levelGridNumber: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  levelGridLabel: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 6 },
  levelGridStars: { flexDirection: 'row', alignItems: 'center' },
  levelGridBadges: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 },
  levelGridEasiestBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelGridEasiestLabel: { fontSize: 12, color: '#16a34a', fontWeight: '700' },
  levelGridHardestBadge: { backgroundColor: '#fee2e2', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelGridHardestLabel: { fontSize: 12, color: '#dc2626', fontWeight: '700' },

  // Practice Screen
  practiceHeader: { position: 'relative', borderRadius: 28, marginHorizontal: 20, paddingTop: 16, padding: 10, paddingBottom: 12, marginBottom: 6, minHeight: 48, marginTop: 12 },
  practiceHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  practiceBackButton: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  practiceHeaderTitle: { fontSize: 20, fontWeight: '700', color: '#ffffff' },
  practiceHeaderSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.9)', marginTop: 3 },
  practiceMetaContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#ffffff' },
  practiceMetaText: { fontSize: 14, fontWeight: '600', color: '#111827' },
  practiceProgressText: { fontSize: 14, color: '#6b7280', fontWeight: '600' },
  progressBarContainer: { height: 6, backgroundColor: '#e5e7eb', marginHorizontal: 20, marginTop: 0, marginBottom: 12, borderRadius: 3, overflow: 'hidden' },
  progressBar: { height: 6, backgroundColor: '#3b82f6', borderRadius: 3 },
  practiceScroll: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 100 },
  questionCard: { backgroundColor: '#ffffff', borderRadius: 24, padding: 16, marginBottom: 8, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3, minHeight: 90 },
  questionText: { fontSize: 24, fontWeight: '800', color: '#111827', textAlign: 'center', lineHeight: 32 },
  wordProblemContainer: { alignItems: 'center', gap: 16 },
  wordProblemImagesContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginBottom: 16, flexWrap: 'wrap' },
  wordProblemImageGroup: { flexDirection: 'row', alignItems: 'center', gap: 4, justifyContent: 'center' },
  wordProblemSmallImage: { marginHorizontal: 1 },
  wordProblemMoreText: { fontSize: 12, fontWeight: '600', color: '#6b7280', marginLeft: 4 },
  wordProblemImageContainer: { width: 80, height: 80, borderRadius: 20, backgroundColor: '#f8fafc', justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  wordProblemImage: {},
  practiceTimerText: { fontSize: 13, fontWeight: '700', color: '#6b7280', marginTop: 4 },
  feedbackRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', gap: 10, marginTop: 12, marginHorizontal: 10 },
  feedbackText: { fontSize: 14, fontWeight: '700', textAlign: 'left', lineHeight: 20, flex: 1 },
  optionsContainer: { marginBottom: 16 },
  optionButton: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 12, marginBottom: 8, borderWidth: 2, gap: 12 },
  optionLabel: { fontSize: 16, fontWeight: '700', minWidth: 28 },
  optionText: { fontSize: 16, fontWeight: '600', flex: 1 },
  practiceNextButtonContainer: { position: 'absolute', bottom: 70, left: 20, right: 20, paddingHorizontal: 0 },
  practiceNextButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 28, borderRadius: 16, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  practiceNextButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },

  resultCard: { backgroundColor: '#ffffff', borderRadius: 28, width: '100%', alignSelf: 'stretch', padding: 24, marginBottom: 24, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  resultTitle: { fontSize: 26, fontWeight: '800', color: '#111827', marginBottom: 12 },
  resultSubtitle: { fontSize: 15, color: '#6b7280', lineHeight: 22, marginBottom: 20 },
  resultBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 16, paddingHorizontal: 18, borderRadius: 20, marginBottom: 20 },
  resultBadgeText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  resultSummary: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  resultSummaryText: { color: '#6b7280', fontSize: 14 },
  resultSummaryValue: { color: '#111827', fontSize: 14, fontWeight: '700' },
  secondaryButton: { marginTop: 14, borderRadius: 22, paddingVertical: 14, alignItems: 'center', backgroundColor: '#f3f4f6' },
  secondaryButtonText: { color: '#111827', fontSize: 16, fontWeight: '700' },

  rankingSection: { backgroundColor: '#ffffff', borderRadius: 24, marginHorizontal: 20, marginBottom: 18, padding: 18, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  rankingHeaderCard: { backgroundColor: '#1d4ed8', borderRadius: 28, padding: 22, marginBottom: 16, width: '100%', alignSelf: 'stretch', shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  rankingHeaderRow: { flexDirection: 'row', alignItems: 'center' },
  rankingHeaderIconWrapper: { width: 52, height: 52, borderRadius: 20, backgroundColor: '#dbeafe', justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  rankingHeaderTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginBottom: 4 },
  rankingHeaderSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 14, lineHeight: 20 },
  rankingTableHeader: { flexDirection: 'row', width: '100%', alignSelf: 'stretch', paddingHorizontal: 20, paddingVertical: 12, marginBottom: 12, borderRadius: 20, backgroundColor: '#f8fafc' },
  rankingTableHeaderLabel: { flex: 1, fontSize: 12, fontWeight: '800', color: '#6b7280', letterSpacing: 0.5 },
  rankingListItem: { flexDirection: 'row', width: '100%', alignSelf: 'stretch', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 20, padding: 16, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
  rankingBadge: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  rankingBadgeText: { fontSize: 16, fontWeight: '800', color: '#1d4ed8' },
  rankingInfo: { flex: 1 },
  rankingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  rankingScore: { fontSize: 18, fontWeight: '800', color: '#111827' },
  rankingTime: { fontSize: 14, fontWeight: '700', color: '#10b981' },
  rankingTopic: { fontSize: 14, color: '#4b5563', lineHeight: 20 },
  rankingDate: { fontSize: 12, color: '#9ca3af', marginLeft: 14, textAlign: 'right' },
  rankingIcon: { marginLeft: 12 },
  rankingEmpty: { fontSize: 15, color: '#6b7280', textAlign: 'center', marginTop: 24 },
  
  // Geometry shape styles
  shapeImageContainer: { alignItems: 'center', justifyContent: 'center', marginVertical: 20 },
  shapeWrapper: { alignItems: 'center', justifyContent: 'center', width: 120, height: 120 },
  triangleShape: { width: 0, height: 0, borderLeftWidth: 60, borderRightWidth: 60, borderBottomWidth: 100, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#f97316' },
  squareShape: { width: 80, height: 80, borderRadius: 8 },
  circleShape: { width: 80, height: 80, borderRadius: 40 },
  rectangleShape: { width: 100, height: 60, borderRadius: 8 },
  pentagonShape: { width: 80, height: 80, borderRadius: 8 },
  hexagonShape: { width: 80, height: 80, borderRadius: 8 },
  diamondShape: { width: 80, height: 80, transform: [{ rotate: '45deg' }], borderRadius: 8 },
  trapezoidShape: { width: 100, height: 60, borderRadius: 8 },
  rhombusShape: { width: 80, height: 80, transform: [{ rotate: '45deg' }], borderRadius: 8 },
  starShape: { width: 80, height: 80, borderRadius: 8 },
  heartShape: { width: 80, height: 80, borderRadius: 8 },
  crescentShape: { width: 80, height: 80, borderRadius: 40 },
  octagonShape: { width: 80, height: 80, borderRadius: 8 },
  parallelogramShape: { width: 100, height: 60, transform: [{ skewX: '-20deg' }], borderRadius: 8 },
  cubeShape: { width: 80, height: 80, borderRadius: 8 },
  pyramidShape: { width: 80, height: 80, borderRadius: 8 },
  sphereShape: { width: 80, height: 80, borderRadius: 40 },
  cylinderShape: { width: 60, height: 80, borderRadius: 30 },
  coneShape: { width: 80, height: 80, borderRadius: 8 },
  
  // Animation styles for practice screens
  correctAnswerAnimation: { 
    transform: [{ scale: 1.1 }],
    shadowColor: '#10b981',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  wrongAnswerAnimation: { 
    transform: [{ translateX: 5 }],
    shadowColor: '#ef4444',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
});
