import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const isCompactWidth = width < 380;
const pagePadding = isCompactWidth ? 12 : 16;
const cardRadius = isCompactWidth ? 16 : 20;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#eef4ff' },
  container: { flex: 1, backgroundColor: '#eef4ff', paddingTop: 0 },
  welcomeSafeArea: { flex: 1, backgroundColor: '#eef4ff' },
  welcomeContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: pagePadding + 8, paddingBottom: 28 },
  welcomeMascot: { marginBottom: 18 },
  welcomeCharacter: { width: isCompactWidth ? 158 : 178, height: isCompactWidth ? 184 : 204, justifyContent: 'flex-start', alignItems: 'center', marginBottom: 18 },
  welcomeHair: { width: isCompactWidth ? 88 : 98, height: 36, borderTopLeftRadius: 38, borderTopRightRadius: 38, borderBottomLeftRadius: 18, borderBottomRightRadius: 18, backgroundColor: '#111827', marginBottom: -22, zIndex: 2 },
  welcomeFace: { width: isCompactWidth ? 88 : 100, height: isCompactWidth ? 88 : 100, borderRadius: isCompactWidth ? 34 : 38, backgroundColor: '#f7c59f', justifyContent: 'center', alignItems: 'center', borderWidth: 4, borderColor: '#ffffff', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  welcomeBoyHairLine: { position: 'absolute', top: 0, width: isCompactWidth ? 72 : 80, height: 22, borderBottomLeftRadius: 22, borderBottomRightRadius: 22, backgroundColor: '#111827' },
  welcomeEyeRow: { flexDirection: 'row', gap: 18, marginBottom: 14 },
  welcomeEye: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#111827' },
  welcomeSmile: { width: 38, height: 18, borderBottomWidth: 4, borderBottomColor: '#111827', borderRadius: 20 },
  welcomeNeck: { width: 24, height: 16, backgroundColor: '#f7c59f', marginTop: -2 },
  welcomeBody: { width: isCompactWidth ? 118 : 132, height: isCompactWidth ? 72 : 80, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  welcomeShirt: { width: isCompactWidth ? 82 : 92, height: isCompactWidth ? 68 : 76, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderBottomLeftRadius: 18, borderBottomRightRadius: 18, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: '#ffffff' },
  welcomeShirtText: { color: '#ffffff', fontSize: 28, fontWeight: '900' },
  welcomeArm: { position: 'absolute', top: 10, width: 18, height: 58, borderRadius: 9, backgroundColor: '#f7c59f' },
  welcomeLeftArm: { left: 12 },
  welcomeRightArm: { right: 12 },
  welcomeBadge: { position: 'absolute', right: 4, bottom: 16, width: 44, height: 44, borderRadius: 16, backgroundColor: '#10b981', justifyContent: 'center', alignItems: 'center', borderWidth: 4, borderColor: '#ffffff' },
  welcomeEyebrow: { color: '#2563eb', fontSize: 13, fontWeight: '800', marginBottom: 10, textTransform: 'uppercase' },
  welcomeTitle: { color: '#111827', fontSize: isCompactWidth ? 25 : 29, lineHeight: isCompactWidth ? 32 : 36, fontWeight: '900', textAlign: 'center', marginBottom: 12 },
  welcomeSubtitle: { color: '#4b5563', fontSize: isCompactWidth ? 16 : 17, lineHeight: isCompactWidth ? 23 : 25, textAlign: 'center', maxWidth: 330 },
  welcomeMiniGrid: { flexDirection: 'row', gap: 10, marginTop: 24, marginBottom: 28 },
  welcomeMiniTile: { width: isCompactWidth ? 58 : 64, height: isCompactWidth ? 52 : 58, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  welcomeMiniText: { fontSize: 17, fontWeight: '900' },
  welcomeNextButton: { minWidth: 168, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, backgroundColor: '#2563eb', borderRadius: 18, paddingVertical: 14, paddingHorizontal: 24, shadowColor: '#1d4ed8', shadowOpacity: 0.22, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  welcomeNextText: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: pagePadding, marginTop: isCompactWidth ? 4 : 8, marginBottom: isCompactWidth ? 4 : 6 },
  topBarTitleGroup: { flex: 1, paddingRight: 10 },
  topBarActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  appTitle: { fontSize: isCompactWidth ? 23 : 26, fontWeight: '800', color: '#111827' },
  pageSubtitle: { fontSize: isCompactWidth ? 13 : 15, color: '#6b7280', marginTop: 4 },
  settingsButton: { width: isCompactWidth ? 40 : 44, height: isCompactWidth ? 40 : 44, borderRadius: 14, backgroundColor: '#ffffff', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  pointsCard: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 20, padding: 16, borderRadius: 20, backgroundColor: '#ffffff', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6, marginBottom: 20 },
  pointsTextGroup: { marginLeft: 12 },
  pointsLabel: { fontSize: 12, color: '#6b7280' },
  pointsValue: { fontSize: 20, fontWeight: '800', color: '#111827', marginTop: 2 },
  scroll: { paddingHorizontal: pagePadding, paddingTop: 4, paddingBottom: 88 },
  homeHero: { minHeight: isCompactWidth ? 116 : 132, borderRadius: cardRadius, backgroundColor: '#ffffff', marginBottom: 14, paddingVertical: isCompactWidth ? 12 : 14, paddingHorizontal: isCompactWidth ? 14 : 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', shadowColor: '#000', shadowOpacity: 0.07, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 5 },
  homeHeroTextGroup: { flex: 1, paddingRight: 8 },
  homeHeroEyebrow: { color: '#f97316', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  homeHeroTitle: { color: '#111827', fontSize: isCompactWidth ? 25 : 29, lineHeight: isCompactWidth ? 31 : 35, fontWeight: '900', marginTop: 2 },
  homeHeroMascot: { marginRight: isCompactWidth ? -4 : 0 },
  homeBubbleRow: { flexDirection: 'row', gap: 7, marginTop: 10 },
  homeBubble: { minWidth: isCompactWidth ? 42 : 46, height: isCompactWidth ? 34 : 36, borderRadius: 14, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 },
  homeBubbleText: { fontSize: isCompactWidth ? 14 : 15, fontWeight: '900' },
  homeTopicGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  homeSectionHeader: { marginTop: 6, marginBottom: 12 },
  homeSectionTitle: { color: '#111827', fontSize: isCompactWidth ? 18 : 20, fontWeight: '800' },
  homeSectionSubtitle: { color: '#64748b', fontSize: isCompactWidth ? 12 : 13, lineHeight: 18, marginTop: 3 },
  topicCard: { width: '31.6%', alignItems: 'center', justifyContent: 'center', padding: isCompactWidth ? 8 : 10, borderRadius: 18, marginBottom: 10, minHeight: isCompactWidth ? 92 : 102, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 5 },
  cardIconWrapper: { width: isCompactWidth ? 38 : 42, height: isCompactWidth ? 38 : 42, borderRadius: 15, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.22)', marginBottom: 8 },
  cardTextGroup: { alignItems: 'center', justifyContent: 'center', minHeight: 32 },
  cardTitle: { color: '#ffffff', fontSize: isCompactWidth ? 12 : 13, lineHeight: isCompactWidth ? 15 : 16, fontWeight: '900', textAlign: 'center' },
  cardSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: isCompactWidth ? 12 : 13, lineHeight: isCompactWidth ? 17 : 18 },
  cardChevronWrapper: { width: 32, height: 32, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.16)' },
  title: { fontSize: 22, fontWeight: '800', color: '#111827', marginHorizontal: 16, marginBottom: 8 },
  description: { fontSize: 15, color: '#6b7280', marginHorizontal: 16 },
  starInfo: { fontSize: 15, color: '#6b7280', marginHorizontal: 16, marginBottom: 16 },
  levelGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', paddingHorizontal: 16 },
  levelButton: { backgroundColor: '#10b981', margin: 4, padding: 12, borderRadius: 10, alignItems: 'center', width: 60 },
  levelText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  starRow: { flexDirection: 'row', marginTop: 6 },
  introHeader: { position: 'relative', borderRadius: cardRadius, marginHorizontal: pagePadding, padding: 8, paddingBottom: 8, marginBottom: 6, minHeight: 44, justifyContent: 'center', marginTop: isCompactWidth ? 4 : 8 },
  headerBack: { position: 'absolute', left: 16, top: 18, width: 36, height: 36, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  headerBackInline: { width: 34, height: 34, borderRadius: 11, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  introTitle: { color: '#ffffff', fontSize: isCompactWidth ? 17 : 19, fontWeight: '800', marginBottom: 0, flexShrink: 1 },
  introSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: isCompactWidth ? 13 : 14, lineHeight: 20, marginTop: 6, flexShrink: 1 },
  headerExamplesRow: { flexDirection: 'row', flexWrap: 'wrap' },
  headerExampleChip: { backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 12, paddingVertical: 6, paddingHorizontal: 10, marginBottom: 6, marginRight: 6 },
  headerExampleText: { color: '#ffffff', fontSize: 12, lineHeight: 16 },
  introScroll: { paddingHorizontal: pagePadding, paddingBottom: 76 },
  sectionTitle: { fontSize: 15, fontWeight: '900', color: '#111827', marginBottom: 8, marginTop: 2 },
  examplesRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  exampleCard: { backgroundColor: '#ffffff', borderRadius: 16, padding: 10, marginBottom: 10, width: '48%', minHeight: 50, justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 9, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
  exampleText: { fontSize: isCompactWidth ? 12 : 13, color: '#111827', lineHeight: isCompactWidth ? 16 : 18, fontWeight: '800', textAlign: 'center' },
  introText: { fontSize: 15, color: '#4b5563', lineHeight: 24, marginTop: 8 },
  descriptionCard: { backgroundColor: '#ffffff', borderRadius: cardRadius, marginHorizontal: 0, padding: pagePadding, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroCard: { backgroundColor: '#ffffff', borderRadius: cardRadius, marginHorizontal: 0, padding: isCompactWidth ? 12 : 14, marginBottom: 10, shadowColor: '#000', shadowOpacity: 0.07, shadowRadius: 13, shadowOffset: { width: 0, height: 7 }, elevation: 5 },
  heroEquation: { fontSize: isCompactWidth ? 23 : 26, fontWeight: '800', textAlign: 'center', marginBottom: 12 },
  heroEquationText: { fontSize: isCompactWidth ? 23 : 26, fontWeight: '800' },
  heroDivider: { display: 'none', height: 1, backgroundColor: '#e5e7eb', marginVertical: 8 },
  heroDescription: { display: 'none', fontSize: 14, color: '#6b7280', lineHeight: 20, textAlign: 'center' },
  primaryButton: { minHeight: 48, marginTop: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: isCompactWidth ? 12 : 14, borderRadius: 16, paddingHorizontal: 20, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  buttonIcon: { marginRight: 10 },
  primaryButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  
  // Addition Intro
  equationBoxRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 12, gap: 6, flexWrap: 'wrap' },
  numberBox: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, minWidth: 45, alignItems: 'center' },
  numberBoxText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  operatorText: { fontSize: 18, fontWeight: '700', color: '#111827', marginHorizontal: 3 },
  
  // Ordering Intro
  orderingSequence: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 10, gap: 3, flexWrap: 'wrap' },
  orderingNumber: { fontSize: 24, fontWeight: '700' },
  orderingComma: { fontSize: 18, color: '#111827', marginHorizontal: 2 },
  orderingArrow: { alignItems: 'center', marginVertical: 6 },
  
  // Sudoku Intro
  sudokuContainer: { alignItems: 'center', marginVertical: 10 },
  sudokuRow: { flexDirection: 'row' },
  sudokuCell: { width: isCompactWidth ? 42 : 50, height: isCompactWidth ? 42 : 50, justifyContent: 'center', alignItems: 'center', borderColor: '#d1d5db', borderWidth: 1 },
  sudokuText: { fontSize: 16, fontWeight: '700', color: '#111827' },
  
  // Counting Intro
  countingHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  countingBadge: { backgroundColor: '#ffffff', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 12, marginBottom: 6 },
  countingBadgeText: { color: '#0ea5e9', fontSize: 16, fontWeight: '800' },
  countingHeaderTitles: { flex: 1 },
  countingNumbersRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: isCompactWidth ? 7 : 10, marginBottom: 14, flexWrap: 'wrap' },
  countingNumber: { fontSize: isCompactWidth ? 26 : 30, fontWeight: '700' },
  applesRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: isCompactWidth ? 7 : 10, marginBottom: 20, flexWrap: 'wrap' },
  appleBubble: { width: isCompactWidth ? 38 : 44, height: isCompactWidth ? 38 : 44, borderRadius: 22, backgroundColor: '#fef2f2', justifyContent: 'center', alignItems: 'center' },
  appleEmoji: { fontSize: 24 },
  exampleCardLarge: { width: '48%', minHeight: isCompactWidth ? 92 : 104 },
  exampleCardLabel: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 6 },
  exampleCardText: { fontSize: 13, color: '#4b5563', lineHeight: 20 },
  exampleAppleRow: { flexDirection: 'row', marginTop: 12, gap: 8 },
  appleEmojiSmall: { fontSize: 18 },
  
  // Geometry Intro
  shapesRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', marginVertical: 20, flexWrap: 'wrap', gap: 12 },
  shapeItem: { alignItems: 'center', gap: 8 },
  shapeLabel: { fontSize: 12, color: '#6b7280', fontWeight: '600' },
  triangle: { width: 0, height: 0, backgroundColor: 'transparent', borderLeftWidth: 30, borderRightWidth: 30, borderBottomWidth: 52, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#f97316' },
  square: { width: 60, height: 60, borderRadius: 8 },
  circle: { width: 60, height: 60, borderRadius: 30 },
  
  // Word Problems Intro
  wordProblemScene: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginVertical: 16, flexWrap: 'wrap' },
  cartContainer: { justifyContent: 'center', alignItems: 'center' },
  priceTagsRow: { flexDirection: 'row', gap: 12 },
  priceTag: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12, position: 'relative' },
  priceText: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  questionMark: { fontSize: 40, fontWeight: '700', color: '#6b7280' },
  
  // Video Lessons Intro
  videoPlayerContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 20, marginVertical: 12 },
  videoPlaceholder: { width: 120, height: 80, backgroundColor: '#e5e7eb', borderRadius: 12, justifyContent: 'center', alignItems: 'center', position: 'relative' },
  playButtonOverlay: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#3b82f6', justifyContent: 'center', alignItems: 'center' },
  bookStack: { width: 80, height: 100, position: 'relative' },
  book: { position: 'absolute', width: 70, height: 80, borderRadius: 4 },

  // Video Lessons Screen
  videoScroll: { paddingHorizontal: pagePadding, paddingTop: isCompactWidth ? 8 : 10, paddingBottom: 90 },
  videoPageHeader: { marginBottom: 10 },
  videoPageTitle: { fontSize: isCompactWidth ? 22 : 24, fontWeight: '900', textAlign: 'center' },
  videoPageSubtitle: { color: '#64748b', fontSize: isCompactWidth ? 13 : 14, lineHeight: 20, textAlign: 'center', marginTop: 6, paddingHorizontal: 8 },
  videoCard: { backgroundColor: '#ffffff', borderWidth: 1.5, borderRadius: cardRadius, padding: isCompactWidth ? 10 : 12, marginBottom: 10, minHeight: isCompactWidth ? 86 : 94, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.07, shadowRadius: 12, elevation: 4 },
  videoThumbnailFrame: { position: 'relative', width: isCompactWidth ? 92 : 104, height: isCompactWidth ? 60 : 68, borderRadius: 15, overflow: 'hidden', marginRight: 12, backgroundColor: '#0f172a' },
  videoThumbnail: { width: '100%', height: '100%' },
  videoOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.24)' },
  videoPlayButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(239,68,68,0.94)', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 5 },
  videoPlayIcon: { marginLeft: 2, transform: [{ scale: 0.74 }] },
  videoLessonPill: { position: 'absolute', top: 6, left: 6, minWidth: 22, height: 22, backgroundColor: 'rgba(15,23,42,0.76)', borderRadius: 11, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  videoLessonPillText: { color: '#ffffff', fontSize: 11, fontWeight: '900' },
  videoCardBody: { flex: 1, justifyContent: 'center' },
  videoTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  videoTitle: { flex: 1, fontSize: isCompactWidth ? 15 : 16, lineHeight: isCompactWidth ? 19 : 21, fontWeight: '900' },
  videoDescription: { color: '#64748b', fontSize: 13, lineHeight: 19 },
  videoModalSafeArea: { flex: 1, backgroundColor: '#000000' },
  videoModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10, backgroundColor: '#000000' },
  videoModalBackButton: { width: 40, height: 40, borderRadius: 14, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)' },
  videoModalTitle: { color: '#ffffff', fontSize: 15, fontWeight: '800', flex: 1, marginHorizontal: 10, textAlign: 'center' },
  videoModeButton: { minWidth: 78, minHeight: 36, borderRadius: 14, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 10, backgroundColor: 'rgba(255,255,255,0.12)' },
  videoModeButtonText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  videoWebView: { flex: 1, backgroundColor: '#000000' },
  videoLoadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#000000' },
  videoLoadingText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  videoErrorContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#000000', padding: 20 },
  videoErrorText: { color: '#ffffff', fontSize: 16, lineHeight: 22, textAlign: 'center' },
  videoRetryButton: { marginTop: 16, paddingHorizontal: 18, paddingVertical: 11, borderRadius: 14, backgroundColor: '#ffffff' },
  videoRetryButtonText: { color: '#111827', fontSize: 14, fontWeight: '800' },
  
  // Level Selector
  levelHeader: { borderRadius: cardRadius, marginHorizontal: pagePadding, padding: 12, paddingBottom: 12, marginBottom: 10, flexDirection: 'row', alignItems: 'flex-start', marginTop: isCompactWidth ? 4 : 8 },
  headerTitleGroup: { flex: 1, marginLeft: 16 },
  levelSelectorTitle: { color: '#ffffff', fontSize: 24, fontWeight: '800', marginBottom: 4 },
  levelSelectorSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 14, lineHeight: 20 },
  levelScroll: { paddingHorizontal: 20, paddingBottom: 100 },
  selectLevelTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 16, marginTop: 8 },
  
  // Level Button
  levelButtonContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, paddingRight: 12 },
  levelCircle: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  levelNumber: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  starsContainer: { flexDirection: 'row', gap: 4 },
  
  // Difficulty Indicator
  difficultyIndicator: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 24, paddingHorizontal: 12 },
  easiestSelectorLabel: { fontSize: 12, color: '#10b981', fontWeight: '600' },
  hardestSelectorLabel: { fontSize: 12, color: '#ef4444', fontWeight: '600' },
  
  // Level Detail Screen
  levelDetailCard: { backgroundColor: '#ffffff', borderRadius: 28, width: '100%', marginBottom: 0, overflow: 'visible', alignSelf: 'stretch', marginHorizontal: 20 },
  levelDetailHeader: { position: 'relative', borderRadius: cardRadius, marginHorizontal: pagePadding, paddingTop: 14, padding: 12, paddingBottom: 12, marginBottom: 10, minHeight: 48, marginTop: isCompactWidth ? 4 : 8 },
  levelDetailHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  levelDetailHeaderBack: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 12, marginRight: 12 },
  headerContentGroup: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 60 },
  categoryIcon: { width: 76, height: 76, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  screenHeaderIcon: { width: 42, height: 42, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 10, backgroundColor: 'rgba(255,255,255,0.18)' },
  levelDetailHeaderTitleGroup: { flex: 1, justifyContent: 'center' },
  introHeaderContent: { marginTop: 0, flexDirection: 'row', alignItems: 'center' },
  introHeaderTitleGroup: { flex: 1, marginLeft: 10, justifyContent: 'center', minHeight: 34 },
  practiceHeaderContent: { marginTop: 0, flexDirection: 'row', alignItems: 'center' },
  practiceHeaderTextGroup: { flex: 1 },
  levelTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginBottom: 4 },
  levelSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 13, lineHeight: 18 },
  levelDetailScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 150 },
  fullScreenScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 150 },
  levelBody: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 24 },
  levelBodyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  easiestBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelDetailButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f8fafc', borderRadius: 20, paddingVertical: 16, paddingHorizontal: 12, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  levelDetailCircle: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  levelDetailNumber: { color: '#ffffff', fontSize: 20, fontWeight: '800' },
  levelDetailInfo: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  levelDetailLabel: { fontSize: 16, fontWeight: '700', color: '#111827' },
  levelDetailStars: { flexDirection: 'row', alignItems: 'center' },
  starSpacing: { marginLeft: 6 },
  levelBodyFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingHorizontal: 20 },
  hardestBadge: { backgroundColor: '#fee2e2', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  easiestLabel: { fontSize: 12, color: '#16a34a', fontWeight: '700' },
  hardestLabel: { fontSize: 12, color: '#dc2626', fontWeight: '700' },

  // Level Grid Screen (New Layout)
  levelGridHeader: { position: 'relative', borderRadius: cardRadius, marginHorizontal: pagePadding, paddingTop: 12, padding: 8, paddingBottom: 8, marginBottom: 6, minHeight: 44, marginTop: isCompactWidth ? 4 : 8 },
  levelGridHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  levelGridHeaderBack: { width: 36, height: 36, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 12, marginRight: 12 },
  levelGridHeaderContent: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  levelGridHeaderIcon: { width: 42, height: 42, borderRadius: 14, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)', marginRight: 10 },
  levelGridHeaderText: { flex: 1 },
  levelGridTitle: { color: '#ffffff', fontSize: 20, fontWeight: '800', marginBottom: 3 },
  levelGridDescription: { color: 'rgba(255,255,255,0.9)', fontSize: 13, lineHeight: 18 },
  levelGridScroll: { flexGrow: 1, paddingHorizontal: pagePadding, paddingBottom: 72 },
  levelGridCard: { backgroundColor: '#ffffff', borderRadius: cardRadius, padding: isCompactWidth ? 12 : 14, marginBottom: 16, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  levelGridPromptRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  levelGridSelectTitle: { fontSize: isCompactWidth ? 18 : 20, fontWeight: '900', color: '#111827' },
  levelGridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 0 },
  levelGridItem: { width: '18.4%', minHeight: isCompactWidth ? 68 : 74, backgroundColor: '#f8fafc', borderRadius: 18, borderWidth: 1.5, paddingVertical: isCompactWidth ? 8 : 10, paddingHorizontal: 2, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  levelGridCircle: { width: isCompactWidth ? 34 : 38, height: isCompactWidth ? 34 : 38, borderRadius: 19, justifyContent: 'center', alignItems: 'center', marginBottom: 6 },
  levelGridNumber: { color: '#ffffff', fontSize: isCompactWidth ? 16 : 17, fontWeight: '900' },
  levelGridLabel: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 6 },
  levelGridStars: { flexDirection: 'row', alignItems: 'center', transform: [{ scale: isCompactWidth ? 0.82 : 0.92 }] },
  levelGridBadges: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 },
  levelGridEasiestBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelGridEasiestLabel: { fontSize: 12, color: '#16a34a', fontWeight: '700' },
  levelGridHardestBadge: { backgroundColor: '#fee2e2', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelGridHardestLabel: { fontSize: 12, color: '#dc2626', fontWeight: '700' },

  // Practice Screen
  practiceHeader: { position: 'relative', borderRadius: cardRadius, marginHorizontal: pagePadding, paddingTop: 8, padding: 8, paddingBottom: 8, marginBottom: 4, minHeight: 44, marginTop: isCompactWidth ? 4 : 8 },
  practiceHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  practiceBackButton: { width: 34, height: 34, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  practiceHeaderTitle: { fontSize: isCompactWidth ? 17 : 19, fontWeight: '700', color: '#ffffff' },
  practiceHeaderSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.9)', marginTop: 3 },
  practiceMetaContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: pagePadding, paddingVertical: isCompactWidth ? 8 : 10, backgroundColor: '#ffffff' },
  practiceMetaText: { fontSize: 14, fontWeight: '600', color: '#111827' },
  practiceProgressText: { fontSize: 14, color: '#6b7280', fontWeight: '600' },
  progressBarContainer: { height: 6, backgroundColor: '#e5e7eb', marginHorizontal: pagePadding, marginTop: 0, marginBottom: 8, borderRadius: 3, overflow: 'hidden' },
  progressBar: { height: 6, backgroundColor: '#3b82f6', borderRadius: 3 },
  practiceScrollView: { flex: 1 },
  practiceScroll: { paddingHorizontal: pagePadding, paddingTop: isCompactWidth ? 10 : 14, paddingBottom: 18 },
  questionCard: { backgroundColor: '#ffffff', borderRadius: cardRadius, padding: isCompactWidth ? 14 : 16, marginBottom: 4, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3, minHeight: 80 },
  questionText: { fontSize: isCompactWidth ? 18 : 20, fontWeight: '800', color: '#111827', textAlign: 'center', lineHeight: isCompactWidth ? 25 : 28 },
  wordProblemContainer: { alignItems: 'center', gap: 16 },
  wordProblemImagesContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginBottom: 16, flexWrap: 'wrap' },
  wordProblemImageGroup: { flexDirection: 'row', alignItems: 'center', gap: 4, justifyContent: 'center' },
  wordProblemSmallImage: { marginHorizontal: 1 },
  wordProblemMoreText: { fontSize: 12, fontWeight: '600', color: '#6b7280', marginLeft: 4 },
  wordProblemImageContainer: { width: 80, height: 80, borderRadius: 20, backgroundColor: '#f8fafc', justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  wordProblemImage: {},
  practiceTimerText: { fontSize: 13, fontWeight: '700', color: '#6b7280', marginTop: 4 },
  feedbackRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', gap: 10, marginTop: 12, marginHorizontal: 10 },
  feedbackText: { fontSize: 14, fontWeight: '700', textAlign: 'left', lineHeight: 20, flex: 1 },
  optionsContainer: { marginBottom: 16 },
  optionButton: { minHeight: 52, flexDirection: 'row', alignItems: 'center', paddingVertical: isCompactWidth ? 12 : 14, paddingHorizontal: 14, borderRadius: 12, marginBottom: 8, borderWidth: 2, gap: 10 },
  optionLabel: { fontSize: 16, fontWeight: '700', minWidth: 28 },
  optionText: { fontSize: 16, fontWeight: '600', flex: 1 },
  practiceNextButtonContainer: { paddingHorizontal: pagePadding, paddingTop: 8, paddingBottom: 14, backgroundColor: '#eef4ff' },
  practiceNextButton: { minHeight: 48, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, paddingVertical: 12, paddingHorizontal: 20, borderRadius: 14, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  practiceNextButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '700' },
  geometryNextButtonInlineContainer: { marginTop: 2, marginBottom: 24 },

  resultCard: { backgroundColor: '#ffffff', borderRadius: cardRadius, alignSelf: 'stretch', padding: isCompactWidth ? 18 : 24, marginHorizontal: pagePadding, marginBottom: 24, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  resultMascot: { alignSelf: 'center', marginBottom: 12 },
  resultTitle: { fontSize: isCompactWidth ? 23 : 26, fontWeight: '800', color: '#111827', marginBottom: 12, textAlign: 'center' },
  resultSubtitle: { fontSize: 15, color: '#6b7280', lineHeight: 22, marginBottom: 20, textAlign: 'center' },
  resultBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 16, paddingHorizontal: 18, borderRadius: 20, marginBottom: 20 },
  resultBadgeText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  resultSummaryPanel: { backgroundColor: '#f8fafc', borderRadius: 18, paddingHorizontal: 14, marginBottom: 2 },
  resultSummary: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  resultSummaryLast: { borderBottomWidth: 0 },
  resultSummaryText: { color: '#6b7280', fontSize: 14 },
  resultSummaryValue: { color: '#111827', fontSize: 14, fontWeight: '700' },
  secondaryButton: { minHeight: 48, marginTop: 14, borderRadius: 22, paddingVertical: 14, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f3f4f6' },
  secondaryButtonText: { color: '#111827', fontSize: 16, fontWeight: '700' },

  rankingSection: { backgroundColor: '#ffffff', borderRadius: cardRadius, marginHorizontal: pagePadding, marginBottom: 18, padding: 18, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  rankingHeaderCard: { backgroundColor: '#1d4ed8', borderRadius: cardRadius, padding: isCompactWidth ? 12 : 16, marginHorizontal: pagePadding, marginBottom: 10, alignSelf: 'stretch', shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  rankingHeaderRow: { flexDirection: 'row', alignItems: 'center' },
  rankingHeaderIconWrapper: { width: 44, height: 44, borderRadius: 16, backgroundColor: '#dbeafe', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  rankingHeaderTextGroup: { flex: 1 },
  rankingHeaderTitle: { color: '#ffffff', fontSize: isCompactWidth ? 18 : 20, fontWeight: '800', marginBottom: 3 },
  rankingHeaderSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: isCompactWidth ? 12 : 13, lineHeight: 18 },
  rankingTableHeader: { flexDirection: 'row', marginHorizontal: pagePadding, alignSelf: 'stretch', paddingHorizontal: isCompactWidth ? 12 : 20, paddingVertical: 10, marginBottom: 10, borderRadius: 16, backgroundColor: '#f8fafc' },
  rankingTableHeaderLabel: { flex: 1, fontSize: 12, fontWeight: '800', color: '#6b7280', letterSpacing: 0.5 },
  rankingListItem: { flexDirection: 'row', marginHorizontal: pagePadding, alignSelf: 'stretch', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: cardRadius, padding: isCompactWidth ? 12 : 16, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
  rankingBadge: { width: isCompactWidth ? 36 : 40, height: isCompactWidth ? 36 : 40, borderRadius: 20, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  rankingBadgeText: { fontSize: 16, fontWeight: '800', color: '#1d4ed8' },
  rankingInfo: { flex: 1 },
  rankingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  rankingScore: { fontSize: isCompactWidth ? 16 : 18, fontWeight: '800', color: '#111827' },
  rankingTime: { fontSize: isCompactWidth ? 13 : 14, fontWeight: '700', color: '#10b981' },
  rankingTopic: { fontSize: 14, color: '#4b5563', lineHeight: 20 },
  rankingDate: { fontSize: 12, color: '#9ca3af', marginLeft: 10, textAlign: 'right', maxWidth: isCompactWidth ? 74 : 96 },
  rankingIcon: { marginLeft: isCompactWidth ? 6 : 12 },
  rankingEmpty: { fontSize: 15, color: '#6b7280', textAlign: 'center', marginTop: 24 },
  
  // Geometry shape styles
  shapeImageContainer: { alignItems: 'center', justifyContent: 'center', marginVertical: 20 },
  geometryQuestionText: { fontSize: isCompactWidth ? 15 : 16, lineHeight: isCompactWidth ? 21 : 23, fontWeight: '700' },
  shapeWrapper: { alignItems: 'center', justifyContent: 'center', width: 120, height: 120 },
  triangleShape: { width: 0, height: 0, borderLeftWidth: 60, borderRightWidth: 60, borderBottomWidth: 100, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#f97316' },
  squareShape: { width: 80, height: 80, borderRadius: 8 },
  circleShape: { width: 80, height: 80, borderRadius: 40 },
  rectangleShape: { width: 100, height: 60, borderRadius: 8 },
  pentagonShape: { width: 92, height: 92, alignItems: 'center', justifyContent: 'flex-end' },
  pentagonTop: { width: 0, height: 0, borderLeftWidth: 46, borderRightWidth: 46, borderBottomWidth: 40, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  pentagonBody: { width: 92, height: 48, borderBottomLeftRadius: 10, borderBottomRightRadius: 10 },
  hexagonShape: { width: 100, height: 92, alignItems: 'center', justifyContent: 'center' },
  hexagonTop: { width: 56, height: 0, borderLeftWidth: 22, borderRightWidth: 22, borderBottomWidth: 20, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  hexagonMiddle: { width: 100, height: 52 },
  hexagonBottom: { width: 56, height: 0, borderLeftWidth: 22, borderRightWidth: 22, borderTopWidth: 20, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  diamondShape: { width: 80, height: 80, transform: [{ rotate: '45deg' }], borderRadius: 8 },
  trapezoidShape: { width: 76, height: 0, borderLeftWidth: 24, borderRightWidth: 24, borderBottomWidth: 72, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  rhombusShape: { width: 88, height: 70, transform: [{ skewX: '-18deg' }], borderRadius: 8 },
  starShape: { width: 80, height: 80, borderRadius: 8 },
  heartShape: { width: 80, height: 80, borderRadius: 8 },
  crescentShape: { width: 80, height: 80, borderRadius: 40, position: 'relative' },
  octagonShape: { width: 94, height: 94, alignItems: 'center', justifyContent: 'center' },
  octagonCap: { width: 58, height: 18 },
  octagonMiddle: { width: 94, height: 58 },
  parallelogramShape: { width: 100, height: 62, transform: [{ skewX: '-20deg' }], borderRadius: 8 },
  cubeShape: { width: 96, height: 90, position: 'relative', alignItems: 'center', justifyContent: 'center' },
  cubeFront: { position: 'absolute', left: 14, top: 28, width: 58, height: 58, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  cubeTop: { position: 'absolute', left: 23, top: 10, width: 58, height: 28, borderRadius: 7, transform: [{ skewX: '-32deg' }] },
  cubeSide: { position: 'absolute', left: 70, top: 21, width: 24, height: 58, borderRadius: 7, transform: [{ skewY: '-32deg' }] },
  pyramidShape: { width: 0, height: 0, borderLeftWidth: 52, borderRightWidth: 52, borderBottomWidth: 90, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  pyramidCenterLine: { position: 'absolute', top: 22, left: -1, width: 2, height: 66, backgroundColor: 'rgba(255,255,255,0.55)' },
  sphereShape: { width: 84, height: 84, borderRadius: 42, position: 'relative', shadowColor: '#1d4ed8', shadowOpacity: 0.25, shadowRadius: 8, shadowOffset: { width: 0, height: 5 }, elevation: 4 },
  sphereHighlight: { position: 'absolute', top: 14, left: 18, width: 22, height: 14, borderRadius: 11, backgroundColor: 'rgba(255,255,255,0.5)' },
  cylinderShape: { width: 74, height: 96, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  cylinderBody: { position: 'absolute', top: 14, width: 74, height: 70, borderRadius: 16 },
  cylinderTop: { position: 'absolute', top: 6, width: 74, height: 24, borderRadius: 37, borderWidth: 3, borderColor: '#bbf7d0', backgroundColor: '#34d399' },
  cylinderBottom: { position: 'absolute', bottom: 4, width: 74, height: 24, borderRadius: 37, borderWidth: 3, borderColor: '#bbf7d0', backgroundColor: 'rgba(16,185,129,0.92)' },
  coneShape: { width: 96, height: 96, alignItems: 'center', justifyContent: 'flex-end' },
  coneTriangle: { width: 0, height: 0, borderLeftWidth: 42, borderRightWidth: 42, borderBottomWidth: 82, borderLeftColor: 'transparent', borderRightColor: 'transparent' },
  coneBase: { width: 84, height: 22, borderRadius: 42, marginTop: -12, backgroundColor: '#fca5a5', borderWidth: 2, borderColor: '#fecaca' },
  
  // Animation styles for practice screens
  correctAnswerAnimation: { 
    transform: [{ scale: 1.1 }],
    shadowColor: '#10b981',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  wrongAnswerAnimation: { 
    transform: [{ translateX: 5 }],
    shadowColor: '#ef4444',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
});
