import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#eef4ff' },
  container: { flex: 1, backgroundColor: '#eef4ff', paddingTop: 20 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, marginBottom: 16 },
  logo: { fontSize: 24, fontWeight: '800', color: '#1d4ed8' },
  profileButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#ffffff', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 4, shadowOffset: { width: 0, height: 2 }, elevation: 3 },
  scroll: { flexGrow: 1, paddingHorizontal: 20 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 12 },
  categories: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  categoryCard: { backgroundColor: '#ffffff', borderRadius: 20, padding: 20, marginBottom: 16, width: '48%', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  categoryIcon: { width: 56, height: 56, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  categoryTitle: { fontSize: 16, fontWeight: '800', color: '#111827', marginBottom: 4 },
  categorySubtitle: { fontSize: 13, color: '#6b7280', lineHeight: 18 },
  introHeader: { position: 'relative', borderRadius: 28, marginHorizontal: 20, padding: 12, paddingBottom: 16, marginBottom: 8, minHeight: 56, justifyContent: 'center' },
  introTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginBottom: 0, flexShrink: 1 },
  introSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: 15, lineHeight: 22, marginTop: 8, flexShrink: 1 },
  headerExamplesRow: { flexDirection: 'row', flexWrap: 'wrap' },
  headerExampleChip: { backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 16, paddingVertical: 8, paddingHorizontal: 12, marginBottom: 8, marginRight: 8 },
  headerExampleText: { color: '#ffffff', fontSize: 13, lineHeight: 18 },
  introScroll: { paddingHorizontal: 20, paddingBottom: 30 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 12, marginTop: 10 },
  examplesRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  exampleCard: { backgroundColor: '#ffffff', borderRadius: 20, padding: 14, marginBottom: 12, width: '48%', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  exampleText: { fontSize: 14, color: '#111827', lineHeight: 20 },
  introText: { fontSize: 15, color: '#4b5563', lineHeight: 24, marginTop: 8 },
  descriptionCard: { backgroundColor: '#ffffff', borderRadius: 24, marginHorizontal: 20, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroCard: { backgroundColor: '#ffffff', borderRadius: 28, marginHorizontal: 20, padding: 24, marginBottom: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroEquation: { fontSize: 30, fontWeight: '800', textAlign: 'center', marginBottom: 16 },
  heroEquationText: { fontSize: 30, fontWeight: '800' },
  heroDivider: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 12 },
  heroDescription: { fontSize: 15, color: '#6b7280', lineHeight: 22, textAlign: 'center' },
  primaryButton: { marginTop: 24, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 16, borderRadius: 22, paddingHorizontal: 28, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  buttonIcon: { marginRight: 10 },
  primaryButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  
  // Practice Screen
  practiceHeader: { position: 'relative', borderRadius: 28, marginHorizontal: 20, paddingTop: 24, padding: 12, paddingBottom: 16, marginBottom: 8, minHeight: 56 },
  practiceHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start' },
  practiceBackButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  practiceHeaderTitle: { fontSize: 22, fontWeight: '700', color: '#111827' },
  practiceHeaderSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.9)', marginTop: 4 },
  practiceMetaContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#ffffff' },
  practiceMetaText: { fontSize: 14, fontWeight: '600', color: '#111827' },
  practiceProgressText: { fontSize: 14, color: '#6b7280', fontWeight: '600' },
  progressBarContainer: { height: 6, backgroundColor: '#e5e7eb', marginHorizontal: 20, marginTop: 0, marginBottom: 12, borderRadius: 3, overflow: 'hidden' },
  progressBar: { height: 6, backgroundColor: '#3b82f6', borderRadius: 3 },
  practiceScroll: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 100 },
  questionCard: { backgroundColor: '#ffffff', borderRadius: 24, padding: 24, marginBottom: 32, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3, minHeight: 140 },
  questionText: { fontSize: 24, fontWeight: '800', color: '#111827', textAlign: 'center', lineHeight: 32 },
  practiceTimerText: { fontSize: 13, fontWeight: '700', color: '#6b7280', marginTop: 4 },
  feedbackRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', gap: 10, marginTop: 12, marginHorizontal: 10 },
  feedbackText: { fontSize: 14, fontWeight: '700', textAlign: 'left', lineHeight: 20, flex: 1 },
  optionsContainer: { marginBottom: 24 },
  optionButton: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 16, marginBottom: 12, borderWidth: 2, gap: 12 },
  optionLabel: { fontSize: 16, fontWeight: '700', minWidth: 28 },
  optionText: { fontSize: 16, fontWeight: '600', flex: 1 },
  practiceBottomActions: { flexDirection: 'row', justifyContent: 'flex-start', gap: 20, paddingBottom: 20 },
  practiceIconButton: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#f3f4f6', justifyContent: 'center', alignItems: 'center' },
  practiceNextButtonContainer: { position: 'absolute', bottom: 20, left: 20, right: 20, paddingHorizontal: 0 },
  practiceNextButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 28, borderRadius: 16, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  practiceNextButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },

  // Geometry shape styles
  shapeImageContainer: { alignItems: 'center', justifyContent: 'center', marginVertical: 20 },
  shapeWrapper: { alignItems: 'center', justifyContent: 'center', width: 120, height: 120 },
  triangleShape: { width: 0, height: 0, borderLeftWidth: 60, borderRightWidth: 60, borderBottomWidth: 100, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#f97316' },
  squareShape: { width: 80, height: 80, borderRadius: 8 },
  circleShape: { width: 80, height: 80, borderRadius: 40 },
  rectangleShape: { width: 100, height: 60, borderRadius: 8 },
  pentagonShape: { width: 80, height: 80, borderRadius: 8 },
  hexagonShape: { width: 80, height: 80, borderRadius: 8 },
  diamondShape: { width: 80, height: 80, transform: [{ rotate: '45deg' }], borderRadius: 8 },
  trapezoidShape: { width: 100, height: 60, borderRadius: 8 },
  rhombusShape: { width: 80, height: 80, transform: [{ rotate: '45deg' }], borderRadius: 8 },
  starShape: { width: 80, height: 80, borderRadius: 8 },
  heartShape: { width: 80, height: 80, borderRadius: 8 },
  crescentShape: { width: 80, height: 80, borderRadius: 40 },
  octagonShape: { width: 80, height: 80, borderRadius: 8 },
  parallelogramShape: { width: 100, height: 60, transform: [{ skewX: '-20deg' }], borderRadius: 8 },
  cubeShape: { width: 80, height: 80, borderRadius: 8 },
  pyramidShape: { width: 80, height: 80, borderRadius: 8 },
  sphereShape: { width: 80, height: 80, borderRadius: 40 },
  cylinderShape: { width: 60, height: 80, borderRadius: 30 },
  coneShape: { width: 80, height: 80, borderRadius: 8 },
});
