import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#eef4ff' },
  container: { flex: 1, backgroundColor: '#eef4ff', paddingTop: 20 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, marginBottom: 20 },
  appTitle: { fontSize: 30, fontWeight: '800', color: '#111827' },
  pageSubtitle: { fontSize: 15, color: '#6b7280', marginTop: 6 },
  settingsButton: { width: 44, height: 44, borderRadius: 16, backgroundColor: '#ffffff', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  pointsCard: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 20, padding: 16, borderRadius: 20, backgroundColor: '#ffffff', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6, marginBottom: 20 },
  pointsTextGroup: { marginLeft: 12 },
  pointsLabel: { fontSize: 12, color: '#6b7280' },
  pointsValue: { fontSize: 20, fontWeight: '800', color: '#111827', marginTop: 2 },
  scroll: { paddingHorizontal: 20, paddingBottom: 30 },
  topicCard: { flexDirection: 'row', alignItems: 'center', padding: 18, borderRadius: 24, marginBottom: 16, minHeight: 98, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  cardIconWrapper: { width: 48, height: 48, borderRadius: 16, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)' },
  cardTextGroup: { marginLeft: 16, flex: 1 },
  cardTitle: { color: '#ffffff', fontSize: 17, fontWeight: '700', marginBottom: 6 },
  cardSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: 13, lineHeight: 18 },
  title: { fontSize: 24, fontWeight: '800', color: '#111827', marginHorizontal: 20, marginBottom: 10 },
  description: { fontSize: 16, color: '#6b7280', marginHorizontal: 20 },
  starInfo: { fontSize: 16, color: '#6b7280', marginHorizontal: 20, marginBottom: 20 },
  levelGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', paddingHorizontal: 20 },
  levelButton: { backgroundColor: '#10b981', margin: 5, padding: 14, borderRadius: 12, alignItems: 'center', width: 64 },
  levelText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  starRow: { flexDirection: 'row', marginTop: 6 },
  introHeader: { position: 'relative', borderRadius: 28, marginHorizontal: 20, padding: 22, paddingBottom: 26, marginBottom: 16, minHeight: 100, justifyContent: 'center' },
  headerBack: { position: 'absolute', left: 20, top: 22, width: 42, height: 42, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center' },
  introTitle: { color: '#ffffff', fontSize: 26, fontWeight: '800', marginBottom: 0, maxWidth: '72%' },
  introSubtitle: { color: 'rgba(255,255,255,0.95)', fontSize: 15, lineHeight: 22, marginTop: 8, maxWidth: '72%' },
  headerExamplesRow: { flexDirection: 'row', flexWrap: 'wrap' },
  headerExampleChip: { backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 16, paddingVertical: 8, paddingHorizontal: 12, marginBottom: 8, marginRight: 8 },
  headerExampleText: { color: '#ffffff', fontSize: 13, lineHeight: 18 },
  introScroll: { paddingHorizontal: 20, paddingBottom: 30 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 12, marginTop: 10 },
  examplesRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  exampleCard: { backgroundColor: '#ffffff', borderRadius: 20, padding: 14, marginBottom: 12, width: '48%', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  exampleText: { fontSize: 14, color: '#111827', lineHeight: 20 },
  introText: { fontSize: 15, color: '#4b5563', lineHeight: 24, marginTop: 8 },
  descriptionCard: { backgroundColor: '#ffffff', borderRadius: 24, marginHorizontal: 20, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroCard: { backgroundColor: '#ffffff', borderRadius: 28, marginHorizontal: 20, padding: 24, marginBottom: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  heroEquation: { fontSize: 30, fontWeight: '800', textAlign: 'center', marginBottom: 16 },
  heroEquationText: { fontSize: 30, fontWeight: '800' },
  heroDivider: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 12 },
  heroDescription: { fontSize: 15, color: '#6b7280', lineHeight: 22, textAlign: 'center' },
  primaryButton: { marginTop: 24, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 16, borderRadius: 22, paddingHorizontal: 28, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  buttonIcon: { marginRight: 10 },
  primaryButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  
  // Addition Intro
  equationBoxRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 16, gap: 8, flexWrap: 'wrap' },
  numberBox: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 12, minWidth: 50, alignItems: 'center' },
  numberBoxText: { color: '#ffffff', fontSize: 18, fontWeight: '700' },
  operatorText: { fontSize: 20, fontWeight: '700', color: '#111827', marginHorizontal: 4 },
  
  // Ordering Intro
  orderingSequence: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginVertical: 12, gap: 4 },
  orderingNumber: { fontSize: 26, fontWeight: '700' },
  orderingComma: { fontSize: 20, color: '#111827', marginHorizontal: 2 },
  orderingArrow: { alignItems: 'center', marginVertical: 8 },
  
  // Sudoku Intro
  sudokuContainer: { alignItems: 'center', marginVertical: 12 },
  sudokuRow: { flexDirection: 'row' },
  sudokuCell: { width: 56, height: 56, justifyContent: 'center', alignItems: 'center', borderColor: '#d1d5db', borderRightWidth: 1, borderBottomWidth: 1 },
  sudokuText: { fontSize: 18, fontWeight: '700', color: '#111827' },
  
  // Counting Intro
  countingHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  countingBadge: { backgroundColor: '#ffffff', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 14, marginBottom: 8 },
  countingBadgeText: { color: '#0ea5e9', fontSize: 18, fontWeight: '800' },
  countingHeaderTitles: { flex: 1 },
  countingNumbersRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 12, marginBottom: 18 },
  countingNumber: { fontSize: 34, fontWeight: '800' },
  applesRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, marginBottom: 20 },
  appleBubble: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#fef2f2', justifyContent: 'center', alignItems: 'center' },
  appleEmoji: { fontSize: 24 },
  exampleCardLarge: { width: '48%', minHeight: 110 },
  exampleCardLabel: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 6 },
  exampleCardText: { fontSize: 13, color: '#4b5563', lineHeight: 20 },
  exampleAppleRow: { flexDirection: 'row', marginTop: 12, gap: 8 },
  appleEmojiSmall: { fontSize: 18 },
  
  // Geometry Intro
  shapesRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', marginVertical: 20 },
  shapeItem: { alignItems: 'center', gap: 8 },
  shapeLabel: { fontSize: 12, color: '#6b7280', fontWeight: '600' },
  triangle: { width: 0, height: 0, backgroundColor: 'transparent', borderLeftWidth: 30, borderRightWidth: 30, borderBottomWidth: 52, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderBottomColor: '#f97316' },
  square: { width: 60, height: 60, borderRadius: 8 },
  circle: { width: 60, height: 60, borderRadius: 30 },
  
  // Word Problems Intro
  wordProblemScene: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 16, marginVertical: 16, flexWrap: 'wrap' },
  cartContainer: { justifyContent: 'center', alignItems: 'center' },
  priceTagsRow: { flexDirection: 'row', gap: 12 },
  priceTag: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 12, position: 'relative' },
  priceText: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  questionMark: { fontSize: 40, fontWeight: '700', color: '#6b7280' },
  
  // Video Lessons Intro
  videoPlayerContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 20, marginVertical: 12 },
  videoPlaceholder: { width: 120, height: 80, backgroundColor: '#e5e7eb', borderRadius: 12, justifyContent: 'center', alignItems: 'center', position: 'relative' },
  playButtonOverlay: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#3b82f6', justifyContent: 'center', alignItems: 'center' },
  bookStack: { width: 80, height: 100, position: 'relative' },
  book: { position: 'absolute', width: 70, height: 80, borderRadius: 4 },
  
  // Level Selector
  levelHeader: { borderRadius: 28, marginHorizontal: 20, padding: 20, paddingBottom: 24, marginBottom: 16, flexDirection: 'row', alignItems: 'flex-start' },
  headerTitleGroup: { flex: 1, marginLeft: 16 },
  levelSelectorTitle: { color: '#ffffff', fontSize: 24, fontWeight: '800', marginBottom: 4 },
  levelSelectorSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 14, lineHeight: 20 },
  levelScroll: { paddingHorizontal: 20, paddingBottom: 30 },
  selectLevelTitle: { fontSize: 18, fontWeight: '800', color: '#111827', marginBottom: 16, marginTop: 8 },
  
  // Level Button
  levelButtonContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, paddingRight: 12 },
  levelCircle: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  levelNumber: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  starsContainer: { flexDirection: 'row', gap: 4 },
  
  // Difficulty Indicator
  difficultyIndicator: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 24, paddingHorizontal: 12 },
  easiestSelectorLabel: { fontSize: 12, color: '#10b981', fontWeight: '600' },
  hardestSelectorLabel: { fontSize: 12, color: '#ef4444', fontWeight: '600' },
  
  // Level Detail Screen
  levelDetailCard: { backgroundColor: '#ffffff', borderRadius: 28, width: '100%', marginBottom: 0, overflow: 'hidden', alignSelf: 'stretch', marginHorizontal: 0 },
  levelDetailHeader: { padding: 20, paddingBottom: 24, flexDirection: 'row', alignItems: 'flex-start', position: 'relative', minHeight: 110 },
  levelDetailHeaderBack: { position: 'absolute', left: 16, top: 16, zIndex: 10, width: 40, height: 40, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 14 },
  headerContentGroup: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 0 },
  categoryIcon: { width: 76, height: 76, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  screenHeaderIcon: { width: 56, height: 56, borderRadius: 18, justifyContent: 'center', alignItems: 'center', marginRight: 14, backgroundColor: 'rgba(255,255,255,0.18)' },
  levelDetailHeaderTitleGroup: { flex: 1, marginLeft: 16, marginTop: 0 },
  introHeaderContent: { marginTop: 16, flexDirection: 'row', alignItems: 'center' },
  practiceHeaderContent: { marginTop: 16, flexDirection: 'row', alignItems: 'center' },
  practiceHeaderTextGroup: { flex: 1 },
  levelTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginBottom: 4 },
  levelSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 13, lineHeight: 18 },
  levelDetailScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 12 },
  fullScreenScroll: { flexGrow: 1, paddingHorizontal: 0, paddingBottom: 20 },
  levelBody: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 24 },
  levelBodyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  easiestBadge: { backgroundColor: '#dcfce7', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  levelDetailButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f8fafc', borderRadius: 20, paddingVertical: 16, paddingHorizontal: 16, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  levelDetailCircle: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  levelDetailNumber: { color: '#ffffff', fontSize: 20, fontWeight: '800' },
  levelDetailInfo: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  levelDetailLabel: { fontSize: 16, fontWeight: '700', color: '#111827' },
  levelDetailStars: { flexDirection: 'row', alignItems: 'center' },
  starSpacing: { marginLeft: 6 },
  levelBodyFooter: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, paddingHorizontal: 4 },
  hardestBadge: { backgroundColor: '#fee2e2', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18 },
  easiestLabel: { fontSize: 12, color: '#16a34a', fontWeight: '700' },
  hardestLabel: { fontSize: 12, color: '#dc2626', fontWeight: '700' },

  // Practice Screen
  practiceHeader: { flexDirection: 'column', alignItems: 'flex-start', paddingHorizontal: 16, paddingVertical: 16, backgroundColor: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  practiceBackButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  practiceHeaderTitle: { fontSize: 18, fontWeight: '700', color: '#111827', marginTop: 12 },
  practiceHeaderSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.9)', marginTop: 4 },
  practiceMetaContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#ffffff' },
  practiceMetaText: { fontSize: 14, fontWeight: '600', color: '#111827' },
  practiceProgressText: { fontSize: 14, color: '#6b7280', fontWeight: '600' },
  progressBarContainer: { height: 6, backgroundColor: '#e5e7eb', marginHorizontal: 20, marginTop: 0, marginBottom: 12, borderRadius: 3, overflow: 'hidden' },
  progressBar: { height: 6, backgroundColor: '#3b82f6', borderRadius: 3 },
  practiceScroll: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 100 },
  questionCard: { backgroundColor: '#ffffff', borderRadius: 24, padding: 24, marginBottom: 32, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3, minHeight: 140 },
  questionText: { fontSize: 24, fontWeight: '800', color: '#111827', textAlign: 'center', lineHeight: 32 },
  practiceTimerText: { fontSize: 13, fontWeight: '700', color: '#6b7280', marginTop: 4 },
  feedbackRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', gap: 10, marginTop: 12, marginHorizontal: 10 },
  feedbackText: { fontSize: 14, fontWeight: '700', textAlign: 'left', lineHeight: 20, flex: 1 },
  optionsContainer: { marginBottom: 24 },
  optionButton: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 16, marginBottom: 12, borderWidth: 2, gap: 12 },
  optionLabel: { fontSize: 16, fontWeight: '700', minWidth: 28 },
  optionText: { fontSize: 16, fontWeight: '600', flex: 1 },
  practiceBottomActions: { flexDirection: 'row', justifyContent: 'flex-start', gap: 20, paddingBottom: 20 },
  practiceIconButton: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#f3f4f6', justifyContent: 'center', alignItems: 'center' },
  practiceNextButtonContainer: { position: 'absolute', bottom: 20, left: 20, right: 20, paddingHorizontal: 0 },
  practiceNextButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 28, borderRadius: 16, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  practiceNextButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },

  resultCard: { backgroundColor: '#ffffff', borderRadius: 28, width: '100%', alignSelf: 'stretch', padding: 24, marginBottom: 24, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  resultTitle: { fontSize: 26, fontWeight: '800', color: '#111827', marginBottom: 12 },
  resultSubtitle: { fontSize: 15, color: '#6b7280', lineHeight: 22, marginBottom: 20 },
  resultBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 16, paddingHorizontal: 18, borderRadius: 20, marginBottom: 20 },
  resultBadgeText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  resultSummary: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  resultSummaryText: { color: '#6b7280', fontSize: 14 },
  resultSummaryValue: { color: '#111827', fontSize: 14, fontWeight: '700' },
  secondaryButton: { marginTop: 14, borderRadius: 22, paddingVertical: 14, alignItems: 'center', backgroundColor: '#f3f4f6' },
  secondaryButtonText: { color: '#111827', fontSize: 16, fontWeight: '700' },

  rankingSection: { backgroundColor: '#ffffff', borderRadius: 24, marginHorizontal: 20, marginBottom: 18, padding: 18, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  rankingHeaderCard: { backgroundColor: '#1d4ed8', borderRadius: 28, padding: 22, marginBottom: 16, width: '100%', alignSelf: 'stretch', shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 8 },
  rankingHeaderRow: { flexDirection: 'row', alignItems: 'center' },
  rankingHeaderIconWrapper: { width: 52, height: 52, borderRadius: 20, backgroundColor: '#dbeafe', justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  rankingHeaderTitle: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginBottom: 4 },
  rankingHeaderSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 14, lineHeight: 20 },
  rankingTableHeader: { flexDirection: 'row', width: '100%', alignSelf: 'stretch', paddingHorizontal: 20, paddingVertical: 12, marginBottom: 12, borderRadius: 20, backgroundColor: '#f8fafc' },
  rankingTableHeaderLabel: { flex: 1, fontSize: 12, fontWeight: '800', color: '#6b7280', letterSpacing: 0.5 },
  rankingListItem: { flexDirection: 'row', width: '100%', alignSelf: 'stretch', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 20, padding: 16, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 3 },
  rankingBadge: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  rankingBadgeText: { fontSize: 16, fontWeight: '800', color: '#1d4ed8' },
  rankingInfo: { flex: 1 },
  rankingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  rankingScore: { fontSize: 18, fontWeight: '800', color: '#111827' },
  rankingTime: { fontSize: 14, fontWeight: '700', color: '#10b981' },
  rankingTopic: { fontSize: 14, color: '#4b5563', lineHeight: 20 },
  rankingDate: { fontSize: 12, color: '#9ca3af', marginLeft: 14, textAlign: 'right' },
  rankingIcon: { marginLeft: 12 },
  rankingEmpty: { fontSize: 15, color: '#6b7280', textAlign: 'center', marginTop: 24 },
});
