import { Category } from '../types';

export const categories: Category[] = [
  {
    key: 'addition',
    screen: 'AdditionIntro',
    title: 'Add & Subtract',
    subtitle: 'Sums and differences',
    color: '#3b82f6',
    icon: 'add',
    description: 'Build number power with quick add and subtract games.',
    hero: {
      equationParts: [
        { text: '23', color: '#1d4ed8' },
        { text: ' + ', color: '#111827' },
        { text: '15', color: '#16a34a' },
        { text: ' = ', color: '#111827' },
        { text: '38', color: '#ef4444' },
      ],
      detail: 'Build number power with quick add and subtract games.',
    },
    examples: ['34 + 27 = ?', '56 - 18 = ?'],
  },
  {
    key: 'multiplication',
    screen: 'MultiplicationIntro',
    title: 'Times & Divide',
    subtitle: 'Times tables and division',
    color: '#10b981',
    icon: 'calculator',
    description: 'Play with times tables and division facts.',
    examples: ['6 x 7 = ?', '72 / 9 = ?'],
  },
  {
    key: 'comparison',
    screen: 'ComparisonIntro',
    title: 'Compare',
    subtitle: '>, <, or =',
    color: '#8b5cf6',
    icon: 'swap-horizontal',
    description: 'Pick the bigger number, smaller number, or equal sign.',
    examples: ['25 > 18', '34 < 50', '27 = 27'],
  },
  {
    key: 'ordering',
    screen: 'OrderingIntro',
    title: 'Order',
    subtitle: 'Sort numbers',
    color: '#f97316',
    icon: 'list',
    description: 'Put numbers in the right order.',
    examples: ['3, 8, 1, 6', '9, 4, 7, 2'],
  },
  {
    key: 'sudoku',
    screen: 'SudokuIntro',
    title: 'Sudoku',
    subtitle: 'Logic puzzles',
    color: '#ef4444',
    icon: 'grid',
    description: 'Use clues to fill the grid.',
    examples: ['Easy', 'Medium', 'Hard'],
  },
  {
    key: 'counting',
    screen: 'CountingIntro',
    title: 'Counting',
    subtitle: 'Numbers and patterns',
    color: '#0ea5e9',
    icon: 'keypad',
    description: 'Count objects and spot number patterns.',
    examples: ['Count apples', '2, 4, 6, 8, __'],
  },
  {
    key: 'geometry',
    screen: 'GeometryIntro',
    title: 'Shapes',
    subtitle: 'Sides and angles',
    color: '#2563eb',
    icon: 'shapes',
    description: 'Find shapes, sides, and angles.',
    examples: ['How many sides?', 'What shape?'],
  },
  {
    key: 'wordproblems',
    screen: 'WordProblemsIntro',
    title: 'Story Math',
    subtitle: 'Mini word puzzles',
    color: '#7c3aed',
    icon: 'book',
    description: 'Solve small stories with math.',
    examples: ['$12 + $5 = ?', '3 bags with 4 apples'],
  },
  {
    key: 'video',
    screen: 'VideoLessonsIntro',
    title: 'Videos',
    subtitle: 'Watch and learn',
    color: '#f59e0b',
    icon: 'play',
    description: 'Watch short math lessons.',
    examples: ['Add Basics', 'Times Tables'],
  },
];
