import { Category } from '../types';

export const categories: Category[] = [
  {
    key: 'addition',
    screen: 'AdditionIntro',
    title: 'Addition & Subtraction',
    subtitle: 'Practice sums and differences',
    color: '#3b82f6',
    icon: 'add',
    description: 'Learn and practice addition and subtraction to build strong basic math skills.',
    hero: {
      equationParts: [
        { text: '23', color: '#1d4ed8' },
        { text: ' + ', color: '#111827' },
        { text: '15', color: '#16a34a' },
        { text: ' = ', color: '#111827' },
        { text: '38', color: '#ef4444' },
      ],
      detail: 'Learn and practice addition and subtraction to build strong basic math skills.',
    },
    examples: ['34 + 27 = ?', '56 - 18 = ?'],
  },
  {
    key: 'multiplication',
    screen: 'MultiplicationIntro',
    title: 'Multiplication & Division',
    subtitle: 'Practice times tables and division',
    color: '#10b981',
    icon: 'calculator',
    description: 'Practice multiplication tables and division to improve speed and accuracy.',
    examples: ['6 × 7 = ?', '72 ÷ 9 = ?'],
  },
  {
    key: 'comparison',
    screen: 'ComparisonIntro',
    title: 'Comparison (>, <, =)',
    subtitle: 'Compare numbers and values',
    color: '#8b5cf6',
    icon: 'swap-horizontal',
    description: 'Compare numbers and choose whether they are greater than, less than, or equal to.',
    examples: ['25 > 18', '34 < 50', '27 = 27'],
  },
  {
    key: 'ordering',
    screen: 'OrderingIntro',
    title: 'Ordering Numbers',
    subtitle: 'Order numbers from least to greatest',
    color: '#f97316',
    icon: 'list',
    description: 'Arrange numbers in order from least to greatest or greatest to least.',
    examples: ['3, 8, 1, 6', '9, 4, 7, 2'],
  },
  {
    key: 'sudoku',
    screen: 'SudokuIntro',
    title: 'Sudoku Logic',
    subtitle: 'Solve sudoku puzzles',
    color: '#ef4444',
    icon: 'grid',
    description: 'Use logic to fill in the grid so that each row, column, and box contains all numbers.',
    examples: ['Easy', 'Medium', 'Hard'],
  },
  {
    key: 'counting',
    screen: 'CountingIntro',
    title: 'Counting & Numbers',
    subtitle: 'Count, write and identify numbers',
    color: '#0ea5e9',
    icon: 'md-numeric',
    description: 'Practice counting, number sequences, place value and number recognition.',
    examples: ['Count the apples', '2, 4, 6, 8, __'],
  },
  {
    key: 'geometry',
    screen: 'GeometryIntro',
    title: 'Geometry & Shapes',
    subtitle: 'Learn about shapes and angles',
    color: '#2563eb',
    icon: 'shapes',
    description: 'Learn about shapes, sides, angles, perimeter and other geometry basics.',
    examples: ['How many sides?', 'What is the shape?'],
  },
  {
    key: 'wordproblems',
    screen: 'WordProblemsIntro',
    title: 'Word Problems',
    subtitle: 'Solve real-life math problems',
    color: '#7c3aed',
    icon: 'book',
    description: 'Solve real-life math problems using addition, subtraction, multiplication and more.',
    examples: ['A book costs $12 and a pen costs $5. How much do they cost together?'],
  },
  {
    key: 'video',
    screen: 'VideoLessonsIntro',
    title: 'Video Lessons',
    subtitle: 'Watch and learn at your own pace',
    color: '#f59e0b',
    icon: 'play',
    description: 'Watch video lessons to learn concepts step by step with clear explanations.',
    examples: ['Addition Basics', 'Multiplication Tables'],
  },
];
